### ISSUE TITLE
A question of  the lidar connection

### ISSUE THREAD

**Issue by u10502101** [yujinrobot/yujin_lidar#24]
I can get the real-time point cloud in Yujin_Lidar_Viewer. When I run the code ''rosrun yujin_yrl_package yrl_pub'', I didn't get the result ''3D Model MODEL YRL3-20 Connected''. And the  output data of  rostopic is 0. How to get the correct real-time data?
![messageImage_1645602762901](https://user-images.githubusercontent.com/92423286/155313565-1a6c5a81-9502-4805-a716-ea96c6caacc6.jpeg)
![S__9986051](https://user-images.githubusercontent.com/92423286/155313662-6bba90c6-54c9-4fef-b80c-20f828618648.jpg)

https://user-images.githubusercontent.com/92423286/155313491-9231e4bf-8f72-4f39-a98b-632c80fa8935.mp4

.

**Comment by Petros626** [comment]
i walk trough this in the next days, if i find a solution i will message you here

**Comment by hyng809** [comment]
Hello 
I have a same problem
How did you solve this problem?

**Comment by Petros626** [comment]
> Hello I have a same problem How did you solve this problem?

Hey,

I would start the following steps:

a) If you working with the ROS Driver, use the yrl_pub.cpp first to start the LiDAR, then you check the settings in the Viewer for example connection, mode (default 1 i guess).

It would be helpful, if screenshots or videos can be posted here, the video from @u10502101 is broken. For my personal experience I must say, that I've worked with the YRL3V2 version of the LiDAR, not the old one. If you have a basic understanding of C++ you could dive into the code and try to find the bug, if there's one.

**Comment by hyng809** [comment]
I did the process in the same order as the video you posted. Similarly, the data part is all 0.
The model I am using now is the YRL2-20 model, and I am using ROS melodic.
Currently I have two problems.

![image](https://user-images.githubusercontent.com/85726781/195540709-bd535312-a45f-4f72-bc96-849e6d921e3c.png)

1) It is saying that the calibration file cannot be found.
I changed the location path to lk.bin absolute path but I am still having the same problem.

![image](https://user-images.githubusercontent.com/85726781/195541013-3545725f-e1b6-4dbc-bb7d-8e45446b99ba.png)

2) When the point cloud is executed, all data parts are displayed as 0.

**Comment by Petros626** [comment]
I have no experience with the old lidar and the calibration file, but yujin robot offers a manual for that I remember. So try from beginning to follow the steps there I would say. If the path of the calibration file is hard coded you should put it in the folder where it belongs to.

And just to be sure, the lidar must be in a room not outside. The zer byte values mean no object is hitted or out of range

**Comment by hyng809** [comment]
Thank you for answer.
I've tried as you advised, but I'm still having the same problem.
