### ISSUE TITLE
instance->setCalibrationFilePath("/home/jykim/catkin_ws/lktest.bin");

### ISSUE THREAD

**Issue by noeperez** [yujinrobot/yujin_lidar#5]
Hello,

in the code of the driver for ros melodic there is this line: 
instance->setCalibrationFilePath("/home/jykim/catkin_ws/lktest.bin");

Obviously, when I execute the node I get the message: "Cannot find the calibration file: /home/jykim/catkin_ws/lktest.bin"
I have been looking for the file lktest.bin in the available sources, but it is missing. 
Could you fix this please?

**Comment by jykim3** [comment]
@noeperez 
The file path /home/jykim/~ is an arbitrary file path.
You should first create a calibration file using either Window or Linux Viewer (A program for visualization).
and put the actual file path as a parameter of the function setCalibrationFilePath.

**Comment by jykim3** [comment]
@noeperez 
Calibration file is an essential binary file that containes calibration data for Yujin LiDAR and is used for ranging.

**Comment by noeperez** [comment]
Thank you very much for the quick response.
I would be great if these steps are explained in the readme file. To indicate the path to the calibration file by ros parameter instead of modifying the code would be also nice.
Thank you again.
